definitions:
  rest.customerParams:
    properties:
      address:
        type: string
      country:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
    required:
    - address
    - country
    - id
    - name
    - phone
    type: object
  rest.orderParams:
    properties:
      cust_id:
        type: integer
      date:
        type: string
      id:
        type: integer
    required:
    - cust_id
    - date
    - id
    type: object
  rest.updateCustomerParams:
    properties:
      address:
        type: string
      country:
        type: string
      name:
        type: string
      phone:
        type: string
    required:
    - address
    - country
    - name
    - phone
    type: object
  rest.updateOrderParams:
    properties:
      cust_id:
        type: integer
      date:
        type: string
    required:
    - cust_id
    - date
    type: object
  views.R:
    properties:
      data: {}
      error_code:
        type: integer
      error_note:
        type: string
      status:
        type: string
    type: object
  views.customer:
    properties:
      address:
        type: string
      country:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
    type: object
  views.order:
    properties:
      cust_id:
        type: integer
      date:
        type: string
      id:
        type: integer
    type: object
info:
  contact:
    email: jasuravazov4@gmail.com
    name: API Support
    url: https://www.linkedin.com/in/jasur-avazov-312686235/
  description: Apelsin crud
  license:
    name: Jasur
    url: https://www.linkedin.com/in/jasur-avazov-312686235/
  title: Apelsin
paths:
  /customer:
    post:
      consumes:
      - application/json
      description: API to create a customer
      parameters:
      - description: create customer request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.customerParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Create customer
      tags:
      - Customer
  /customer/{code}:
    delete:
      consumes:
      - application/json
      description: API to deactivate customer by id
      parameters:
      - description: customer id
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Delete customer
      tags:
      - Customer
    get:
      consumes:
      - application/json
      description: API to get a customer by id
      parameters:
      - description: customer id
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  $ref: '#/definitions/views.customer'
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Read one customer
      tags:
      - Customer
    put:
      consumes:
      - application/json
      description: API to update customer by id
      parameters:
      - description: customer id
        in: path
        name: code
        required: true
        type: string
      - description: update customer request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.updateCustomerParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Update customer
      tags:
      - Customer
  /customers:
    get:
      consumes:
      - application/json
      description: API to get all customers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/views.customer'
                  type: array
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Read all customers
      tags:
      - Customer
  /order:
    post:
      consumes:
      - application/json
      description: API to create a order
      parameters:
      - description: create order request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.orderParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Create order
      tags:
      - Order
  /order/{code}:
    delete:
      consumes:
      - application/json
      description: API to deactivate order by id
      parameters:
      - description: order id
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Delete order
      tags:
      - Order
    get:
      consumes:
      - application/json
      description: API to get a order by id
      parameters:
      - description: order id
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  $ref: '#/definitions/views.order'
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Read one order
      tags:
      - Order
    put:
      consumes:
      - application/json
      description: API to update order by id
      parameters:
      - description: order id
        in: path
        name: code
        required: true
        type: string
      - description: update order request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.updateOrderParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Update order
      tags:
      - Order
  /orders:
    get:
      consumes:
      - application/json
      description: API to get all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/views.order'
                  type: array
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Read all orders
      tags:
      - Order
schemes:
- http
swagger: "2.0"
