definitions:
  rest.Languages:
    properties:
      en:
        type: string
      ru:
        type: string
      uz:
        type: string
    type: object
  rest.districtParams:
    properties:
      code:
        type: string
      code_gni:
        type: string
      code_province:
        type: string
      code_soato:
        type: string
      is_active:
        type: boolean
      title:
        $ref: '#/definitions/rest.Languages'
    required:
    - code
    - code_gni
    - code_province
    - code_soato
    - is_active
    - title
    type: object
  rest.updateDistrictParams:
    properties:
      code_gni:
        type: string
      code_province:
        type: string
      code_soato:
        type: string
      is_active:
        type: boolean
      title:
        $ref: '#/definitions/rest.Languages'
    required:
    - code_gni
    - code_province
    - code_soato
    - is_active
    - title
    type: object
  views.Languages:
    properties:
      en:
        type: string
      ru:
        type: string
      uz:
        type: string
    type: object
  views.R:
    properties:
      data: {}
      error_code:
        type: integer
      error_note:
        type: string
      status:
        type: string
    type: object
  views.district:
    properties:
      code:
        type: string
      code_gni:
        type: string
      code_province:
        type: string
      code_soato:
        type: string
      is_active:
        type: boolean
      title:
        $ref: '#/definitions/views.Languages'
    type: object
info:
  contact:
    email: jasuravazov4@gmail.com
    name: API Support
    url: https://www.instagram.com/
  description: Apelsin crud
  license:
    name: Jasur
    url: https://www.instagram.com/
  title: Apelsin
paths:
  /districts:
    get:
      consumes:
      - application/json
      description: API to get all district
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/views.district'
                  type: array
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Read all district
      tags:
      - District
    post:
      consumes:
      - application/json
      description: API to create a district
      parameters:
      - description: create district request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.districtParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Create district
      tags:
      - District
  /districts/{code}:
    delete:
      consumes:
      - application/json
      description: API to deactivate district by code
      parameters:
      - description: district code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Delete district
      tags:
      - District
    get:
      consumes:
      - application/json
      description: API to get a district by code
      parameters:
      - description: district code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  $ref: '#/definitions/views.district'
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Read one district
      tags:
      - District
    put:
      consumes:
      - application/json
      description: API to update district by code
      parameters:
      - description: district code
        in: path
        name: code
        required: true
        type: string
      - description: update district request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.updateDistrictParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Update district
      tags:
      - District
schemes:
- http
swagger: "2.0"
