definitions:
  rest.categoryParams:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - id
    - name
    type: object
  rest.customerParams:
    properties:
      address:
        type: string
      country:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
    required:
    - address
    - country
    - id
    - name
    - phone
    type: object
  rest.orderParams:
    properties:
      cust_id:
        type: integer
      date:
        type: string
      id:
        type: integer
    required:
    - cust_id
    - date
    - id
    type: object
  rest.productParams:
    properties:
      category_id:
        type: integer
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      photo:
        type: string
      price:
        type: number
    required:
    - category_id
    - description
    - id
    - name
    - photo
    - price
    type: object
  rest.updateCategoryParams:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  rest.updateCustomerParams:
    properties:
      address:
        type: string
      country:
        type: string
      name:
        type: string
      phone:
        type: string
    required:
    - address
    - country
    - name
    - phone
    type: object
  rest.updateOrderParams:
    properties:
      cust_id:
        type: integer
      date:
        type: string
    required:
    - cust_id
    - date
    type: object
  rest.updateProductParams:
    properties:
      category_id:
        type: integer
      description:
        type: string
      name:
        type: string
      photo:
        type: string
      price:
        type: number
    required:
    - category_id
    - description
    - name
    - photo
    - price
    type: object
  views.R:
    properties:
      data: {}
      error_code:
        type: integer
      error_note:
        type: string
      status:
        type: string
    type: object
  views.category:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  views.customer:
    properties:
      address:
        type: string
      country:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
    type: object
  views.order:
    properties:
      cust_id:
        type: integer
      date:
        type: string
      id:
        type: integer
    type: object
  views.product:
    properties:
      category_id:
        type: integer
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      photo:
        type: string
      price:
        type: number
    type: object
info:
  contact:
    email: jasuravazov4@gmail.com
    name: API Support
    url: https://www.linkedin.com/in/jasur-avazov-312686235/
  description: Apelsin crud
  license:
    name: Jasur
    url: https://www.linkedin.com/in/jasur-avazov-312686235/
  title: Apelsin
paths:
  /categories:
    get:
      consumes:
      - application/json
      description: API to get all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/views.category'
                  type: array
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Read all categories
      tags:
      - Category
  /category:
    post:
      consumes:
      - application/json
      description: API to create a category
      parameters:
      - description: create category request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.categoryParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Create category
      tags:
      - Category
  /category/{code}:
    delete:
      consumes:
      - application/json
      description: API to deactivate category by id
      parameters:
      - description: category id
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Delete category
      tags:
      - Category
    get:
      consumes:
      - application/json
      description: API to get a category by id
      parameters:
      - description: category id
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  $ref: '#/definitions/views.category'
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Read one category
      tags:
      - Category
    put:
      consumes:
      - application/json
      description: API to update category by id
      parameters:
      - description: category id
        in: path
        name: code
        required: true
        type: string
      - description: update category request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.updateCategoryParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Update category
      tags:
      - Category
  /customer:
    post:
      consumes:
      - application/json
      description: API to create a customer
      parameters:
      - description: create customer request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.customerParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Create customer
      tags:
      - Customer
  /customer/{code}:
    delete:
      consumes:
      - application/json
      description: API to deactivate customer by id
      parameters:
      - description: customer id
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Delete customer
      tags:
      - Customer
    get:
      consumes:
      - application/json
      description: API to get a customer by id
      parameters:
      - description: customer id
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  $ref: '#/definitions/views.customer'
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Read one customer
      tags:
      - Customer
    put:
      consumes:
      - application/json
      description: API to update customer by id
      parameters:
      - description: customer id
        in: path
        name: code
        required: true
        type: string
      - description: update customer request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.updateCustomerParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Update customer
      tags:
      - Customer
  /customers:
    get:
      consumes:
      - application/json
      description: API to get all customers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/views.customer'
                  type: array
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Read all customers
      tags:
      - Customer
  /order:
    post:
      consumes:
      - application/json
      description: API to create a order
      parameters:
      - description: create order request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.orderParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Create order
      tags:
      - Order
  /order/{code}:
    delete:
      consumes:
      - application/json
      description: API to deactivate order by id
      parameters:
      - description: order id
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Delete order
      tags:
      - Order
    get:
      consumes:
      - application/json
      description: API to get a order by id
      parameters:
      - description: order id
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  $ref: '#/definitions/views.order'
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Read one order
      tags:
      - Order
    put:
      consumes:
      - application/json
      description: API to update order by id
      parameters:
      - description: order id
        in: path
        name: code
        required: true
        type: string
      - description: update order request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.updateOrderParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Update order
      tags:
      - Order
  /orders:
    get:
      consumes:
      - application/json
      description: API to get all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/views.order'
                  type: array
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Read all orders
      tags:
      - Order
  /product:
    post:
      consumes:
      - application/json
      description: API to create a product
      parameters:
      - description: create product request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.productParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Create product
      tags:
      - Product
  /product/{code}:
    delete:
      consumes:
      - application/json
      description: API to deactivate product by id
      parameters:
      - description: product id
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Delete product
      tags:
      - Product
    get:
      consumes:
      - application/json
      description: API to get a product by id
      parameters:
      - description: product id
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  $ref: '#/definitions/views.product'
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Read one product
      tags:
      - Product
    put:
      consumes:
      - application/json
      description: API to update product by id
      parameters:
      - description: product id
        in: path
        name: code
        required: true
        type: string
      - description: update product request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.updateProductParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.R'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Update product
      tags:
      - Product
  /products:
    get:
      consumes:
      - application/json
      description: API to get all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/views.product'
                  type: array
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/views.R'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.R'
      summary: Read all products
      tags:
      - Product
schemes:
- http
swagger: "2.0"
