DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS "order";
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS detail;
DROP TABLE IF EXISTS invoice;
DROP TABLE IF EXISTS payment;